# Generated by Django 4.2.4 on 2023-08-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_col', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='PSTDateTime',
        ),
    ]
