# Generated by Django 4.2.4 on 2023-08-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_yourmodel_delete_pstdatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='loopiter',
            field=models.IntegerField(default=0),
        ),
    ]
