# Generated by Django 4.2.4 on 2023-08-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0003_yourmodel_loopiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='timezone_field',
            field=models.CharField(default='UTC', max_length=63),
        ),
    ]
