# Generated by Django 4.2.4 on 2023-08-24 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0004_yourmodel_timezone_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yourmodel',
            old_name='timezone_field',
            new_name='timezone',
        ),
    ]
