# Generated by Django 4.2.4 on 2023-08-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0005_rename_timezone_field_yourmodel_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='loopiter',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='timezone',
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='pst_datetime_col',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='utc_datetime_col',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
