# Generated by Django 4.2.4 on 2023-08-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0006_remove_yourmodel_loopiter_remove_yourmodel_timezone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='last_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
