# Generated by Django 4.2.4 on 2023-08-29 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0007_yourmodel_last_update_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='last_update_time',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='pst_datetime_col',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='utc_datetime_col',
        ),
    ]
