# Generated by Django 4.2.4 on 2023-08-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0008_remove_yourmodel_last_update_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='pst_datetime_col',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='utc_datetime_col',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
