# Generated by Django 4.2.4 on 2023-08-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0009_yourmodel_pst_datetime_col_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='pst_datetime_col',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='utc_datetime_col',
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='timezone_col',
            field=models.TextField(default='PST'),
        ),
    ]
