# Generated by Django 4.2.4 on 2023-08-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0010_remove_yourmodel_pst_datetime_col_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='timezone_col',
            field=models.TextField(),
        ),
    ]
