# Generated by Django 4.2.4 on 2023-08-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0011_alter_yourmodel_timezone_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yourmodel',
            name='timezone_col',
            field=models.TextField(default='NONE'),
        ),
    ]
