# Generated by Django 4.2.4 on 2023-08-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0012_alter_yourmodel_timezone_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='timezone_col',
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='datetime_col_PST',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='datetime_col_UTC',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
