# Generated by Django 4.2.4 on 2023-08-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0013_remove_yourmodel_timezone_col_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='datetime_col_PST',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='datetime_col_UTC',
        ),
    ]
