version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=djangoauthapi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sarmad123
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

volumes:
  db:
    driver: local
