# Generated by Django 4.2.5 on 2023-09-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Bronze', 'Bronze'), ('Gold', 'Gold')], default='Silver', max_length=10),
        ),
    ]
